### PR TITLE
node stats: support infinity

### PR DESCRIPTION
**Pull request by fbs**
These values are often float64 but sometimes a string, from the api docs[1]:

> An "Infinity" value for a given flow window indicates that worker
> millis have been spent without any events completing processing

This adds a custom float64 type to enable the use of a custom marshaller.

[1]: https://www.elastic.co/guide/en/logstash/current/node-stats-api.html

fixes: #372

### CODE REVIEW

**Comment by kuskoman** [comment]
@fbs would you mind adding a test to the new type that you created?

**Comment by fbs** [comment]
Still need to update the tests, will work on that.

Guess I also need to target v2/master with this PR, what is the process for that? Shall I open a 2nd PR after this lands?

**Comment by fbs** [comment]
I pushed a fix so the tests pass, but let me figure out how to test the infinity values as well

**Comment by fbs** [comment]
done

**Review by kuskoman — APPROVED** [review]

**Pull request merged**
