### PR TITLE
Add support for pipeline flow metrics

### LINKED ISSUE #118: support for flow metrics
First I would like to thank you for this very valuable project.
Would you please consider to add support for exporting flow metrics as well ?
[https://www.elastic.co/guide/en/logstash/current/node-stats-api.html#flow-stats](https://www.elastic.co/guide/en/logstash/current/node-stats-api.html#flow-stats)

### PR DESCRIPTION
**Pull request by kuskoman**
Closes #118

### CODE REVIEW

**Comment by excalq** [comment]
Flow metrics were added to [Logstash 8.5.0](https://www.elastic.co/guide/en/logstash/8.7/logstash-8-5-0.html#features-8.5.0). I'm still running 8.4, which lacks these. I'll test how this works with the source data missing, before upgrading our Logstash.

**Comment by kuskoman** [comment]
I did not think about it, thanks

**Comment by kuskoman** [comment]
It should default to 0 i think

**Comment by kuskoman** [comment]
#88 would be useful here I guess

**Pull request merged**
