### PR TITLE
Add building multi-arch image to pipeline

### PR DESCRIPTION
**Pull request by arousseau-coveo**
Fix Issue #136 

Run this on my fork buildx seems to be working but I can't test the rest of the pipeline integrations 
https://github.com/arousseau-coveo/logstash-exporter/actions/runs/6027420067/job/16352636745

### CODE REVIEW

**Comment by arousseau-coveo** [comment]
@kuskoman This one is an easy one I think. 
Would you have some time to review it ?

**Comment by kuskoman** [comment]
Error:
```
Run docker save logstash-exporter:latest | gzip > logstash-exporter.tar.gz
Error response from daemon: reference does not exist
```

**Comment by arousseau-coveo** [comment]
Alright with further reading seems like the way it was before is still not supported: https://github.com/docker/buildx/issues/166

I have implemented a fix mentionned in the thread

**Comment by arousseau-coveo** [comment]
Alright @kuskoman  I did my best but the last error in the helm test integrations is hard for me to understand/solve. I try to run all the step on my end and it deployed without issue in my kind cluster. 

I would appreciate bit of help when you have time do to so. 
Thanks

**Pull request merged**
